library(here)
library(tidyverse)
library(readr)
library(broom)
library(janitor)
library(jag2)
library(glmnet)
library(foreach)
library(caret)
library(InformationValue)
library(rsample)
library(pROC)
library(doParallel)
library(metapone)
library(corrplot)
library(RColorBrewer)
library(xtune)
library(crayon)
library(stabs)
library(haven)
library(car)

# no_cores <- detectCores() -1
# cl <- makeCluster(no_cores, type = "FORK")
