---
title: "Empirical Distribution of AUC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---



```{r empirical distribution of auc data setup, include = FALSE, echo = FALSE}
source(fs::path(here::here(),"0_project_setup","!libraries.R"))
source(fs::path(here::here(),"0_project_setup","!directories.R"))
source(fs::path(here::here(),"0_project_setup","!set_exposure_outcome_vars.R"))

sol_data <- read_rds(fs::path(dir_data_analysis, "SOLAR analysis full data.rds"))

chs_data <- read_rds(fs::path(dir_data_analysis, "CHS analysis full data.rds"))

solar_ft <- read_rds(fs::path(dir_data_analysis, "SOLAR feature data all modes.rds"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
```


## Figure S2 Empirical distribution of AUC
```{r empirical distribution of auc chs, echo=TRUE}

auc_df <- read_csv(fs::path(dir_results, 
                   "prediction",
                   "4_auc_random_features_covars.csv"),col_names = FALSE) %>%
  rename(auc = X1)

auc_df %>% ggplot(aes(x = auc)) + 
  geom_histogram(fill = "white", color = "black",bins = 50) +
  geom_histogram(data = subset(auc_df, auc>=0.8422764 & auc<=max(auc)),colour="black", fill="grey", bins = 50) +
  ylim(0, 75) +
  labs( x = "AUC", y = "Count") +
  geom_vline(xintercept = 0.881, linetype = "dashed") +
  annotate(geom = "text",
           label = "AUC: 0.881",
           x = 0.9,
           y = 65) +
  theme_classic()

ggsave(filename = fs::path(dir_reports, "Figure S2. empirical auc distribution of randomly selected reatures and covars.png"), 
       width = 10, height = 6, dpi=300)

# auc7_chs <- data.frame(auc = median(auc_df$auc), ci_low =as.numeric(jag2::qntle_fxn(auc_df$auc, 0.025)), ci_high = as.numeric(jag2::qntle_fxn(auc_df$auc, 0.975)), model = "GRF + SRF + randome metabolites", cohort = "CHS", note = "random selected features + all covars")

```

