## Load data
```{r feature selection data setup, include = FALSE, echo = FALSE}
source(fs::path(here::here(),"0_project_setup","!libraries.R"))
source(fs::path(here::here(),"0_project_setup","!directories.R"))
source(fs::path(here::here(),"0_project_setup","!set_exposure_outcome_vars.R"))

sol_data <- read_rds(fs::path(dir_data_analysis, "SOLAR analysis full data.rds"))

chs_data <- read_rds(fs::path(dir_data_analysis, "CHS analysis full data.rds"))

solar_ft <- read_rds(fs::path(dir_data_analysis, "SOLAR feature data all modes.rds"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
```


# Preparing analysis ready solar and chs data
All continuous features and covariates variables are normalized.
```{r prepare analysis ready data, echo=TRUE}
# solar -------
solar_data <- solar_data %>%
  mutate_at(.vars = vars(all_of(features),age_1, bmi_1, og_glu_5_1, og_glu120_1, tot_chol_1, tag_1 ),
            .funs = list(~scale(.))
            )

# chs ----------------
chs_data <- chs_data %>%
  mutate_at(.vars = vars(all_of(features),age_1, bmi_1, og_glu_5_1, og_glu120_1, tot_chol_1, tag_1),
            .funs = list(~scale(.)))
```


# coefficient comparison of solar and chs
```{r}
solar_coef_df <- read_csv(fs::path(dir_results,"prediction",
                                   "4_solar_model_result_with_annotation_5000.csv"))

chs_coef_df <- read_csv(fs::path(dir_results,"prediction",
                                   "4_chs_model_result_with_annotation_5000.csv"))

full_coef_df <- solar_coef_df %>% mutate(cohort = "SOLAR") %>%
  bind_rows(chs_coef_df%>% mutate(cohort = "CHS")) %>%
  mutate(cohort = factor(cohort, levels = c("SOLAR", "CHS")))

### Create Coefficient Plots-----
full_coef_df  %>% filter(term != "(Intercept)") %>%
  ggplot(aes(x = term,y = estimate)) +
  geom_point(size = 1) +
  coord_flip()+
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0) +
  geom_hline(yintercept = 0, linetype = 2) +
  ylab("β (Coefficient)") +
  xlab("Feature") + 
  # ggtitle("CCoefficient Plots") +
  theme(panel.background = element_rect(fill="grey95"), 
          strip.background = element_rect(fill = "white"),
          strip.text.y = element_text(angle = 0, hjust = 0),
        text = element_text(size = 10),
        axis.title.x=element_blank(),
        legend.title = element_blank())+
  coord_flip() +
  facet_wrap(. ~ cohort, 
                    scales = "free_x",
                    ncol = 4)

ggsave(filename = fs::path(dir_reports, "4_Comparison of Coef plots solar and chs.png"), 
       width = 10, height = 6, dpi=300)

### Create metabolites Coefficient Plots-----
full_coef_df  %>% 
  filter(met_name_first %in% c("Taurocholic acid", "Hippuric acid", "Caprylic acid")) %>%
  ggplot(aes(x = met_name_first,y = estimate)) +
  geom_point(size = 1) +
  coord_flip()+
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0) +
  geom_hline(yintercept = 0, linetype = 2, color = "grey") +
  ylab("β (95% CI)") +
  # ggtitle("CCoefficient Plots") +
  theme(panel.background = element_rect(fill="grey95"), 
          strip.background = element_rect(fill = "white"),
          strip.text.y = element_text(angle = 0, hjust = 0),
        text = element_text(size = 8),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.title = element_blank())+
  coord_flip() +
  facet_wrap(. ~ cohort, 
                    scales = "free_x",
                    ncol = 4)

ggsave(filename = fs::path(dir_reports, "Figure 3. Effect estimates for metabolites associated with prediabetes.jpg"), 
       width = 3, height = 1.5, dpi=300)
```

