---
title: "Coefficient plot"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r coefficient plot data setup, include = FALSE, echo = FALSE}
source(fs::path(here::here(),"0_project_setup","!libraries.R"))
source(fs::path(here::here(),"0_project_setup","!directories.R"))
source(fs::path(here::here(),"0_project_setup","!set_exposure_outcome_vars.R"))

sol_data <- read_rds(fs::path(dir_data_analysis, "SOLAR analysis full data.rds"))

chs_data <- read_rds(fs::path(dir_data_analysis, "CHS analysis full data.rds"))

solar_ft <- read_rds(fs::path(dir_data_analysis, "SOLAR feature data all modes.rds"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
```

### Figure 3. Coefficient comparison of SOLAR and CHS
```{r coefficient plot}
solar_coef_df <- read_csv(fs::path(dir_results,"prediction",
                                   "4_solar_model_result_with_annotation_0530.csv"))

chs_coef_df <- read_csv(fs::path(dir_results,"prediction",
                                   "4_chs_model_result_with_annotation_0530.csv"))

full_coef_df <- solar_coef_df %>% mutate(cohort = "SOLAR") %>%
  bind_rows(chs_coef_df %>% mutate(cohort = "CHS")) %>%
  mutate(
    cohort = ifelse(cohort == "SOLAR", "SOLAR (discovery)", "CHS (validation)")) %>%
  mutate(
    cohort = factor(cohort, levels = c("SOLAR (discovery)", "CHS (validation)"))
  )

### Create metabolites Coefficient Plots
full_coef_df  %>% 
  filter(met_name_first %in% c("Taurocholic acid", "Allylphenol sulfate", "Caprylic acid")) %>%
  ggplot(aes(x = met_name_first,y = odds_ratio)) +
  geom_point(size = 1) +
  coord_flip()+
  geom_errorbar(aes(ymin = exp_conf_low,
                    ymax = exp_conf_high),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  scale_x_discrete(limits = c( "Taurocholic acid","Caprylic acid","Allylphenol sulfate")) +
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        text = element_text(size = 10),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.title = element_blank())+
  coord_flip() +
  facet_wrap(. ~ cohort, 
                    scales = "free_x",
                    ncol = 4)

ggsave(filename = fs::path(dir_reports, "Figure 3. Effect estimates for metabolites associated with prediabetes 0522.jpg"),
       width = 3, height = 1.5, dpi=300)
```

