---
title: "ROC curves"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r roc curve data setup, include = FALSE, echo = FALSE}
source(fs::path(here::here(),"0_project_setup","!libraries.R"))
source(fs::path(here::here(),"0_project_setup","!directories.R"))
source(fs::path(here::here(),"0_project_setup","!set_exposure_outcome_vars.R"))

sol_data <- read_rds(fs::path(dir_data_analysis, "SOLAR analysis full data.rds"))

chs_data <- read_rds(fs::path(dir_data_analysis, "CHS analysis full data.rds"))

solar_ft <- read_rds(fs::path(dir_data_analysis, "SOLAR feature data all modes.rds"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
```


## Figure 1 ROC curve of GRF, GRF+SRF, GRF+SRF+metabolites in SOLAR and CHS
```{r roc curve, echo=TRUE}
png(fs::path(dir_reports, 
             "4_roc_curve_solar.png"),
    width = 3000, height = 2000, res = 350)
plot.roc(solar_pred1$diabete_change_di, solar_pred1$pred,
     print.auc = FALSE, col = "#88CCEE", print.auc.y = 0.3, legacy.axes = TRUE)
plot.roc(solar_pred2$diabete_change_di, solar_pred2$pred, 
     print.auc = FALSE, col = "#DDCC77", print.auc.y = 0.4, add = TRUE)
plot.roc(solar_pred4$diabete_change_di,  solar_pred4$pred,
     print.auc = FALSE, col = "#CC6677", print.auc.y = 0.5, add = TRUE)
legend("bottomright", 
       legend = c("Model 1", "Model 2", "Model 3"),
       col = c("#88CCEE", "#DDCC77", "#CC6677"),
       lty = c(1,1,1))
dev.off() 


png(fs::path(dir_reports, 
             "4_roc_curve_CHS.png"),
    width = 3000, height = 2000, res = 350)
plot.roc(chs_pred1$diabete_change_di, chs_pred1$pred,
     print.auc = FALSE, col = "#88CCEE", print.auc.y = 0.3, legacy.axes = TRUE)
plot.roc(chs_pred2$diabete_change_di, chs_pred2$pred, 
     print.auc = FALSE, col = "#DDCC77", print.auc.y = 0.4, add = TRUE)
plot.roc(chs_pred4$diabete_change_di,  chs_pred4$pred,
     print.auc = FALSE, col = "#CC6677", print.auc.y = 0.5, add = TRUE)
legend("bottomright", 
       legend = c("Model 1", "Model 2", "Model 3"),
       col = c("#88CCEE", "#DDCC77", "#CC6677"),
       lty = c(1,1,1))
dev.off() 

```

