---
title: "AUC comparison"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---


```{r auc comparison data setup, include = FALSE, echo = FALSE}
source(fs::path(here::here(),"0_project_setup","!libraries.R"))
source(fs::path(here::here(),"0_project_setup","!directories.R"))
source(fs::path(here::here(),"0_project_setup","!set_exposure_outcome_vars.R"))

sol_data <- read_rds(fs::path(dir_data_analysis, "SOLAR analysis full data.rds"))

chs_data <- read_rds(fs::path(dir_data_analysis, "CHS analysis full data.rds"))

solar_ft <- read_rds(fs::path(dir_data_analysis, "SOLAR feature data all modes.rds"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
```


## Figure 2. AUC comparison of models 

```{r auc comparison plot}
auc <- read_csv(fs::path(dir_results,
                         "prediction",
                         "4_auc_df.csv"))
### Create auc comparision plots-----
model_name <- c("GRF", "GRF + SRF","GRF + metabolites", "GRF + SRF + metabolites","metabolites")

auc <- auc %>% mutate(cohort = factor(cohort, levels = c("SOLAR (discovery)", "CHS (validation)")))

auc %>% filter(model %in% model_name) %>%
  ggplot(aes(x = factor(model, levels = model_name), y = auc, color = cohort)) +
  geom_point(size = 1, position =position_dodge(width = 0.3)) +
  geom_errorbar(aes(ymin = ci_low,
                    ymax = ci_high),
                width = 0.2, 
                position =position_dodge(width = 0.3)) +
  ylab("AUC (95% CI)") +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey") +
  facet_wrap(~cohort) +
  theme(panel.background = element_rect(fill="white"), 
        # panel.grid = element_blank(),
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        text = element_text(size = 18),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        # axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.title = element_blank(),
        legend.position="none",
        axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_manual(values = c("#AF7AC5", "#117A65"))

ggsave(filename = fs::path(dir_reports, "Figure 3. Prediction performance of models.jpg"),
       width = 8, height = 5, dpi=300)
```
```
